name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Add build number to .env
        run: |
          echo "" >> .env
          echo "REACT_APP_BUILD_NUMBER={BUILD_NUMBER}" >> .env

      - name: Replace secret
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "{"
          tokenSuffix: "}"
          files: ".env"
        env:
          TB_URL: ${{ vars.TB_URL }}
          API_DEVICE_ID: ${{ vars.API_DEVICE_ID }}
          TB_PUBLICID: ${{ vars.TB_PUBLICID }}
          BUILD_NUMBER: ${{ github.run_number }}

      # - name: Print .env file content
      #   run: cat .env
        
      - name: Build
        run: npm run build

      - name: List build directory contents
        run: ls -la build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build
          retention-days: 7
          include-hidden-files: true
